### ISSUE TITLE
Evaluate nexus3-cli

### ISSUE THREAD

**Issue by jemrobinson** [alan-turing-institute/nexus-allowlist#6]
Might want to consider using https://gitlab.com/thiagocsf/nexus3-cli instead of maintaining our own nexus bindings.

_Originally posted by @JimMadge in https://github.com/alan-turing-institute/data-safe-haven/issues/1481#issuecomment-1572263077_

**Comment by JimMadge** [comment]
From a quick look, the bindings don't implement all of the API end points we use to enforce the allowlist (including, content selectors, content selector privileges, roles, role assignment).

It also looks like the project may be unmaintained. ~1 year since last changes. I don't think we are in a position to fork or adopt that project as we only need to use a subset of the API.

I will mark this a won't fix and close.
